# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/ethan.k/Desktop/CodingNStuff/python/Pixelto3dVoxel

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/ethan.k/Desktop/CodingNStuff/python/Pixelto3dVoxel

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ethan.k/Desktop/CodingNStuff/python/Pixelto3dVoxel/CMakeFiles /Users/ethan.k/Desktop/CodingNStuff/python/Pixelto3dVoxel//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ethan.k/Desktop/CodingNStuff/python/Pixelto3dVoxel/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pixeltovoxel

# Build rule for target.
pixeltovoxel: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pixeltovoxel
.PHONY : pixeltovoxel

# fast build rule for target.
pixeltovoxel/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pixeltovoxel.dir/build.make CMakeFiles/pixeltovoxel.dir/build
.PHONY : pixeltovoxel/fast

#=============================================================================
# Target rules for targets named process_rays

# Build rule for target.
process_rays: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 process_rays
.PHONY : process_rays

# fast build rule for target.
process_rays/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/process_rays.dir/build.make CMakeFiles/process_rays.dir/build
.PHONY : process_rays/fast

src/pixeltovoxel.o: src/pixeltovoxel.cpp.o
.PHONY : src/pixeltovoxel.o

# target to build an object file
src/pixeltovoxel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pixeltovoxel.dir/build.make CMakeFiles/pixeltovoxel.dir/src/pixeltovoxel.cpp.o
.PHONY : src/pixeltovoxel.cpp.o

src/pixeltovoxel.i: src/pixeltovoxel.cpp.i
.PHONY : src/pixeltovoxel.i

# target to preprocess a source file
src/pixeltovoxel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pixeltovoxel.dir/build.make CMakeFiles/pixeltovoxel.dir/src/pixeltovoxel.cpp.i
.PHONY : src/pixeltovoxel.cpp.i

src/pixeltovoxel.s: src/pixeltovoxel.cpp.s
.PHONY : src/pixeltovoxel.s

# target to generate assembly for a file
src/pixeltovoxel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pixeltovoxel.dir/build.make CMakeFiles/pixeltovoxel.dir/src/pixeltovoxel.cpp.s
.PHONY : src/pixeltovoxel.cpp.s

src/process_rays.o: src/process_rays.cpp.o
.PHONY : src/process_rays.o

# target to build an object file
src/process_rays.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/process_rays.dir/build.make CMakeFiles/process_rays.dir/src/process_rays.cpp.o
.PHONY : src/process_rays.cpp.o

src/process_rays.i: src/process_rays.cpp.i
.PHONY : src/process_rays.i

# target to preprocess a source file
src/process_rays.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/process_rays.dir/build.make CMakeFiles/process_rays.dir/src/process_rays.cpp.i
.PHONY : src/process_rays.cpp.i

src/process_rays.s: src/process_rays.cpp.s
.PHONY : src/process_rays.s

# target to generate assembly for a file
src/process_rays.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/process_rays.dir/build.make CMakeFiles/process_rays.dir/src/process_rays.cpp.s
.PHONY : src/process_rays.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... pixeltovoxel"
	@echo "... process_rays"
	@echo "... src/pixeltovoxel.o"
	@echo "... src/pixeltovoxel.i"
	@echo "... src/pixeltovoxel.s"
	@echo "... src/process_rays.o"
	@echo "... src/process_rays.i"
	@echo "... src/process_rays.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

